---
title: "Math 615 homepage"
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
wk1.date <- as.Date("2019-08-26")
```

This is the landing page for <span style="color:blue">**Statistical Methods for Graduate Research**</span> course taught by [Dr. Robin Donatello](http://www.norcalbiostat.com) for <span style="color:blue">**Fall 2019**</span>.   
This page is used for posting of regular announcements and information for students of the class. 




### `r format(wk1.date+7*16, "%m-%d-%Y")` Week 16: Finals Week

Poster Session - **Thursday**  12/19, 10-12pm Tehama 116.

I am very sorry I cannot make it. Edward Roualdes will supervise and serve as reviewer. 


**Room Setup**

1. Move the tables and chairs away from 7 monitors in the front half of the room. 
2. Presenters going in the first round each picks a monitor and log into Google Drive
    - You can see what round you are in by looking at the peer review Google Form link below. 
    - The keyboards have numbers on them that match a number in the top right of the monitor. 
3. Download your poster as PDF - then <span style="color:red">**Open this file in Adobe**</span>
    - This will let you use the touch screen to zoom in and navigate around the PDF in presentation mode. 

**Presentations**

* Presentations will be conducted in 2 rounds.
    - Edward will read off the names of those going in the first round. 
    - Expect to spend no more than 5-7 minutes at each poster,
* Presenters: Don't read your poster to the audience. Summarize your findings. 
* Audience: Be a good audience. Ask questions. Don't sit down. 
    - This is a conversation between scholars, the presenter is not a teacher at the board. Don't stand like 15 feet away from them.

**Reviews**

* Poster peer review Google Form: https://forms.gle/oFMQ2hqtthZFPq7T7
    - Some paper copies will be available. You still must do data entry later. 
    - You will be expected to review everyone not in your presentation round. This will be 6-7 people. 



<span style="color:red">**Office Hours for Finals Week**</span> 

> OH for Finals Week: All hours will be held in Holt 202   
- Mon: 9-10am, 2-3pm  
- Tue: 10:30-11:30, 8-9pm  (Zoom link in Slack)
- Wed: 9:30-11am   


### `r format(wk1.date+7*15, "%m-%d-%Y")` Week 15: Poster building!

* Poster building week! See the project page for instructions. 
    - Drafts are due Fri 11/13, Peer review on Sun 12/15
    - Final version due to Google Drive by 9am on Thursday. 
* Take Home Final exam 
    - Distributed Wed 12/11 via Slack. 
    - Due Friday 12/20 EOD. 
    - All links to files and for submission in Slack post. 



### `r format(wk1.date+7*14, "%m-%d-%Y")` Week 14: Model building / Model fit

* You've been exploring relationships on variables related to your individual research question all semester. Now is time to bring all this information together and build a 'final' model. 
     - Build a final multivariable model. y ~ x1 + x2 + ...
     - The goal is to explain the variabilty in your response variable, using multiple predictor variables. 
* Model building is cyclical, we'll go over some criteria this week on how to know when to stop and how to compare different models. 
* Poster prep stage IV is due this week - this is the final stage before you build your posters. Pay close attention to the requirement details on the project page. 
    - wrapping up your 'story'
    - describe the limitations to your study
    - propose further work: What can someone *DO* with the information you've found?



### `r format(wk1.date+7*13, "%m-%d-%Y")` Fall Break
Relax, get caught up on sleep. 


### `r format(wk1.date+7*12, "%m-%d-%Y")` Week 13: Generalized Linear Models

* What to do when the response variable is no longer continuous.
* How to include categorical variables in multivariable models. 


### `r format(wk1.date+7*11, "%m-%d-%Y")` Week 12: Multivariable Regression Modeling

* Writing and interpreting multivariable models
* How else can tertiary variable muck up an observed bivariate relationship? Confounding. 
* Start HW10 this week. 


### `r format(wk1.date+7*10, "%m-%d-%Y")` Week 11: Moderation

Let's start to explore how a third variable can effect, or change, a pattern or relationship between two variables. This is called *moderation*, and it introduces a type of analysis called *stratification*. 

We're also going to continue your personal resarch by applying appropriate statistical analyses to your poster prep slides. (Stage III)

### `r format(wk1.date+7*9, "%m-%d-%Y")` Week 10: Correlation and Regression Analysis

* Two ways to assess relationships between two continuous measurements: 
    - Correlation. Is X associated with y?
    - Regression. How much does Y change as X changes? 
    
* Back to reading PMA5. The Applied Stats course notes is the short version. Quiz topics will be out of both. 




### `r format(wk1.date+7*8, "%m-%d-%Y")` Week 9: Inference on multiple groups

The [[Applied Stats]](https://norcalbiostat.github.io/AppliedStatistics_notes/) notebook is being updated to include separate sections for each bivariate analysis. Read through the relevant chapters prior to class. 

* Some board work on ANOVA on Tuesday
* Chi-squared activity with M&M's on Thursday

Each day will have open work time. 


---

### `r format(wk1.date+7*7, "%m-%d-%Y")` Week 8: Statistical Inference

* Active discussion on transformations for normality, and choosing appropriate analyses on Tuesday.
    - Bring your textbook!
* Start Bivariate Inference (hw08) on Thursday.
    - Two sample T-test for a difference in means. 


### `r format(wk1.date+6*7, "%m-%d-%Y")` Week 7: Quantifying Uncertainty, Calculating Probabilities

As we start our next phase of the class working on conducting _Inferential Statistics_, we need to finish learning how to correctly interpret a confidence interval, and how to use known distributions (like the sampling distribution) to calculate probabilities.  

Each day for the next 2 weeks we will cover how to analyze a different combination of response & explanatory variables. Don't wait until the end to do that portion of the HW08. As soon as we cover that topic, do that piece of the HW. 

This week you should also be working on your Poster prep stage II: Showcase your data.  

We're still working out of external resources such as 

* [OpenIntro Statistics textbook Ch5](https://leanpub.com/openintro-statistics)
* Dr. D's [Math 315 course notes](https://norcalbiostat.github.io/MATH315/reading/RAD_course_notes_f19.pdf) 


**Tuesday**  

* Calculating Probabilities under a known distribution [[Hack MD Lec05]](https://hackmd.io/@norcalbiostat/math615_lec05). 
* Additional resource for calculating probabilities
    - [Dr D's course notes ch 3.3](https://www.youtube.com/watch?v=Bv9iY8-UzYw&feature=youtu.be)
    - OpenIntro Statistis [Shiny app](https://gallery.shinyapps.io/dist_calc/)
* Interpreting Confidence intervals as a range of plausible values  
    - Collaborative recap on [[Hack MD Lec06]](https://hackmd.io/@norcalbiostat/math615_lec06) notes on terminology

    
**Thursday**

* Group quiz on interval estimation
* Foundations for how to conduct a thourough hypothesis test.   

---

### `r format(wk1.date+5*7, "%m-%d-%Y")` Week 6: Probability

So far you have been conducting an exploratory data analysis to learn the distributions of your measures, and to assess for any possible relationships in your research. You cannot make any statistical claims about whether or not a relationship is significant at this point. That is under the realm of _inferential statistics_ and will be the topic of the class after Spring break. 

To understand why inferential statistics can be used to make valid claims, we have to learn a little bit about _Probability_ first. If you are rusty on your basic statistics and probability, I recommend getting the OpenIntro textbook as a review. 

This is a much more mathematical section of the course, so be sure to plan your time accordingly. 

**Updates** I have cxl'd HW 6 (research proposal). 

---

### `r format(wk1.date+4*7, "%m-%d-%Y")` Week 5: Describing Relationships between two variables

Goals for the week: 

1. Describe the relationship between two variables using all the same descriptive principles you learned to describe a single variable. (HW05, HackMD lecture notes 04)
2. Start your research poster prep slides. (PPI)

**Housekeeping**

* Monday 2pm OH cancelled this week. Extra OH Monday at 9, and Wed at 9am.
* I will be out of town Wed aft - Sunday. I'll be reachable by Slack still, but mostly not at a computer. Kathy Gray will be covering class on Thursday, which will be mostly an open work day. 


----

### `r format(wk1.date+3*7, "%m-%d-%Y")` Week 4: Describing Distributions of Data

I'm alive!

> OH Cancelled Monday. Sorry, lot of Drs appts in the upcoming weeks that were scheduled months ago. 
> Additional OH Wednesday at 9am

If there's one take home message for this week, is to describe the distribution of variables you need: 

1. a picture
2. summary statistics
3. a complete sentence interpretation

> Re: Homework 03. I will adjusted the grading rubric to downweight the data management portion. 
> We'll continue to work more on data management this week (and for the next few weeks).



---

### `r format(wk1.date+2*7, "%m-%d-%Y")` Week 3: Preparing your data for analysis.

We talked about what a reproducible research pipeline looked like, and started a data management file that imported your research data into your SPC. 

This week we'll talk about how to identify features of data that will need to be changed prior to analysis. We can't cover them all, nor would you remember them all. This is a place where experience and repetition will be the true learning method. Most importantly, when you figure out how to do a "thing".. share that "thing" with others by posting the problem & code solution on the collaborative HackMD notes. You'll thank not only yourself but others later when you come across having to do that "thing" again.. (because it's never just once.) 

----


### `r format(wk1.date+7, "%m-%d-%Y")`: Week 2

Hope everyone had a relaxing 3day weekend. Office hours have been set. Thank you for contributing! 

* Monday 2-3pm Holt 202
* Tuesday 10-11am Holt  202
* Wednesday 2-4pm PHSC 213 (Community Coding)
* Thursday 2-4pm MLIB 442 (Community Coding)

Collaborative Hack MD notes are posted under "Materials" in the nav bar. 

Next up is formulating research hypotheses on your selected data, and setting up a reproducible research pipeline to prepare data for analysis. 

----

### `r format(wk1.date, "%m-%d-%Y")`: Welcome to Fall 19!

* This course website contains all materials except the textbook for this class. Be sure to familarize yourself with the organization. You will be here a lot. Bookmark this page.
* Specifically click on and explore items in the top navigation bar. 
* Take this survey to help choose when I should hold Office Hours: https://forms.gle/6ZTSfrJ2WbyKMfk39 
* We will use Slack to faciliate outside of class discussion, and to replace emails. 
    - Use the link under 'Tools' in the navigation boar of this page to go to our Slack workspace, make an account using your @mail.csuchico.edu email address. 
    - You must download either the desktop app, or the phone app, or both. Do not rely on the browser based version. 

