---
title: "Lecture Slides"
output: 
  html_document:
    toc: TRUE
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse); library(kableExtra);library(stringr); library(pander)
library(lubridate)
options(knitr.table.format = "html", knitr.kable.NA = '') 
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE) 
```

---

### Week 1: Introduction

**Jan 7: Introduction, Spatial Data and Geographic Information:** [pdf](lectures/01_introduction.pdf){target="_blank"} , [html](lectures/01_introduction/index.html){target="_blank"}

### Week 2: R basics and R Markdown

**Jan 13: Introduction R and R Studio:** [pdf](lectures/02_Rbasics.pdf){target="_blank"} , [html](lectures/02_Rbasics/index.html){target="_blank"} , [in-class-excercise](lectures/02_datatypes_inclass.html){target="_blank"},
[in-class-poll-everywhere](lectures/in_class_quiz.pdf){target="_blank"}

**Jan 15: Introduction R Markdown and Literate programming:** [pdf](lectures/03_RMarkdown.pdf){target="_blank"}, 
[html](lectures/03_RMarkdown/index.html){target="_blank"}, 
[in-class-exercise](lectures/03_Rmarkdown_inclass/03_inclass_exercise.zip){target="_blank"}

### Week 3: Doing Data Science

**Jan 22: Introduction to Tidyverse:** [pdf](lectures/04_tidyverse.pdf){target="_blank"} , [html](lectures/04_tidyverse/index.html){target="_blank"}

### Week 4: Representing and Handling Spatial Data

**Jan 27: Locations and Coordinate Systems:** [pdf](lectures/05_locCoordSystems.pdf){target="_blank"} , [html](lectures/05_locCoordSystems/index.html){target="_blank"}

**Jan 29: Spatial Data Types:** [pdf](lectures/06_spatial_datatypes.pdf){target="_blank"}

### Week 5: Finding, Acquiring and Import Spatial Data

**Feb 3: Finding, Acquiring and Importing Spatial Data:** [pdf](lectures/lecture7/sp_findHandle.pdf){target="_blank"}
[html](lectures/lecture7/sp_findHandle.html){target="_blank"}

**Feb 5: Importing and reading Spatial Data:** 
[html](lectures/lecture8/sp_import.html){target="_blank"}, 
[twitter-exercise](lectures/lecture8/GEOG215-Twitter-API_varun.html){target="_blank"}

### Week 6: Data Wrangling and Visualization

**Feb 10: Taming, Tidying, and Transforming your Data:** [pdf](lectures/09_tidyWrangling/wrangle.pdf){target="_blank"}, 
[html](lectures/09_tidyWrangling/wrangle.html){target="_blank"}

**Feb 12: Visualizing your Data:** [pdf](lectures/10_dataViz1/viz1.pdf){target="_blank"}, 
[html](lectures/10_dataViz1/viz1.html){target="_blank"}

### Week 7: Maps, and Asking Spatial Questions

**Feb 17: Visualizing Spatial Data**
[pdf](lectures/11_maps_viz/viz2.pdf){target="_blank"}, 
[html](lectures/11_maps_viz/viz2.html){target="_blank"}

**Feb 19: Asking Spatial Questions**
[pdf](lectures/12_askingQs/geog215_askingQs.pdf){target="_blank"}

### Week 8: Reproducible Research, Midterm practice

**Feb 24: Principles of Reproducible Research**
[pdf](lectures/13_reproducible_research/reproducible.pdf){target="_blank"}, 
[html](lectures/13_reproducible_research/reproducible.html){target="_blank"}

**Feb 26: Practice Midterm**

### Week 9: Exploratory Spatial Data Analysis I

**March 2: Class Project, Intro to ESDA**
[pdf](lectures/15_esda/15_esda.pdf){target="_blank"}, 
[html](lectures/15_esda/15_esda.html){target="_blank"}

**March 4: Distance**
[pdf](lectures/16_esda1_distance/16_esda1_distance.pdf){target="_blank"}, 
[html](lectures/16_esda1_distance/16_esda1_distance.html){target="_blank"}


### Week 12: Revised class logistics and Wrangling Spatial Data

**March 23: Checking in and class updates**
[pdf](lectures/17_class2ndhalf/17_Class2ndHalf.pdf){target="_blank"}, 
[recorded lecture {password-protected}](https://unc.zoom.us/rec/share/uZNHf7vR23NIQ4nns0LBYaorDq21aaa8h3NK_6FZnRyw40DwIwGLVu0b8c0R1XeW){target="_blank"}

**March 25: Wrangling Spatial Data**
[pdf](lectures/18_wranglingSpatialData/18_wranglingSpatialData.pdf){target="_blank"},
[Class Demo](lectures/18_wranglingSpatialData/18_wranglingSpatialData.R){target="_blank"}, 
[recorded lecture {password-protected}](https://unc.zoom.us/rec/share/z-x8KZHprTJOZbPh2UXBXpA7OdXMX6a8gyYY_PoLykcdtKMibhnB8UnZnNcKzqNW){target="_blank"}

### Week 13: Spatial Neighbors and Clustering

**March 30: Spatial Neighborhoods and neighbors**
[pdf](lectures/19_spatialNeighbors/19_spatialNeighbors.pdf){target="_blank"}, 
[recorded lecture {password-protected}](https://unc.zoom.us/rec/share/6-1cN5v1zDhLSM_QtGjTd5ERHNm0T6a81iEfq6AOzh1oWTkazPOg_13O7hOcMzSy){target="_blank"}

**April 1: Spatial Clustering and Autocorrelation**
[pdf](lectures/lecture20/20-GEOG215-SpClusterAutoCor.pdf){target="_blank"}, 
[recorded lecture {password-protected through your sakai credentials}](https://sakai.unc.edu/x/DYlpu4){target="_blank"}

### Week 14: GLobal and Local Spatial Autocorrelation

**April 6: Spatial Autocorrelation: Theory and Concepts**
[pdf](lectures/21_spatialAutocorrelation.pdf){target="_blank"}, 
[recorded lecture {password-protected}](https://unc.zoom.us/rec/share/vcZSaIDf_25LbqPI8krHSqQ6QIKiX6a81yYc_qZbmU55PM5IguS__pKNAX_wzT8i){target="_blank"}

**April 8: Spatial Autocorrelation: Practice**
[recorded lecture {password-protected}](https://unc.zoom.us/rec/share/xe0lJLKv1TtLeJ2O9kryavMEE4K5eaa80CEa8_dczkz43WRRzF7ljzX7Pd2fvKZP){target="_blank"}

### Week 15: Spatial Point Pattern Analysis

**April 6: Spatial Point Pattern Analysis: Theory and Concepts**
[pdf](22_pointpattern.pdf){target="_blank"}, 
[recorded lecture {password-protected}](https://unc.zoom.us/rec/share/wudTK7zu30FIfoHwyXjuY6sPH4bmX6a8gSYZ_KVYnkkFZHELedBICVfHOa51W2LS){target="_blank"}
