---
title: "Readings"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse); library(kableExtra);library(stringr); library(pander)
library(lubridate)
options(knitr.table.format = "html", knitr.kable.NA = '') 
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE) 
```

### Last Updated: `r format(Sys.time(), "%a %b %d %X")` {.tabset .tabset-fade .tabset-pills}

The "Weeks" below correspond to enumerated weeks found in the syllabus schedule. The readings should be completed before the start of class for the corresponding week. For example, readings under week 2 are relevant to the class discussion during week 2, and hence should be completed before the classes in week 2. Please email me immediately if any links are broken!

******

## Week 2 :  Introduction to R

1. Install R and Rstudio [Click for Instructions here](software_resources.html) **[Required]**

2. Install and complete relevant Swirl modules in RStudio [instruction here](readings/wk1/swirl_rprog.html){target="_blank"} **[Required]**

3. Complete the poll everywhere survey [here](https://pollev.com/goelvarun553). **[required]**
You need to register with your unc email address. I will use this survey to help form balanced teams with a mix of programming, GIS skills and subject skills for the  projects.

4. Sign up for the [class Piazza page](https://piazza.com/unc/spring2020/geog215) **[required]** if you have not done so already

4. Chapter 1: Introduction from *Doing Data Science (Schutt & O'Neill, 2013)* :[Excellent and inclusive introduction to Data Science including how it is done in Academia and Industry](http://cdn.oreillystatic.com/oreilly/booksamplers/9781449358655_sampler.pdf) **[Recommended]**

5. [A fun interview with 3 Data Science Stalwarts on Data Science in Everyday life](http://www.sciencefriday.com/segments/solving-lifes-everyday-problems-with-data/) **[Recommended]**
******

---

## Week 3 :  Doing Data Science: Introduction to TidyVerse

1. Read the 2 articles on the Australian Bushfires by the New York Times and BBC
  - <https://www.nytimes.com/interactive/2020/01/02/climate/australia-fires-map.html>
  - <https://www.bbc.com/news/world-australia-50951043>
