---
title: ' Revised Schedule'
---
```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse); library(kableExtra);library(stringr); library(pander)
library(lubridate)
options(knitr.table.format = "html", knitr.kable.NA = '') 
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE) 
```

### Last Updated: `r format(Sys.time(), "%a %b %d %X")` {.tabset .tabset-fade .tabset-pills}

<p>
This is the **revised schedule** for the remainder of the semester starting March 23, 2020 
</p>
```{r}
# Read in schedule

wk_schedule <- read_csv("~/Documents/unc/classes/spring2020/geog215/uncgeog215sp20/course_info/revised_weekly_schedule.csv")
wk_schedule$deliverables[is.na(wk_schedule$deliverables)]<-""
# Set semester start date and format weeks nicely
start.date <- as_date("2020/01/08")
no_wks <- 16
class_seq <- c(seq(no_wks)*7,seq(no_wks)*7+5) %>% sort
class_date <- start.date+class_seq-7
class_date[32] <- "2020-05-04"
class_date <- class_date[-c(1:21)]

wk_schedule <- wk_schedule %>% dplyr::select(-Order) %>% 
  mutate(Date = paste(month(class_date),
                      day(class_date),sep="/"),
         Day = wday(class_date,label=T)) %>%
  transmute(Week = wknum, Day = Day, Date = Date, Topic = topic, 
            Deliverables = deliverables)

# add exams and project 3 dates manually
wk_schedule <- wk_schedule %>% add_row(Week = "", Day = "Sun",Date = "4/19", Topic = "**Draft Project Report due at 11:59pm EST**", Deliverables ="",.after = 8) %>%
  add_row(Week = "", Day = "Mon",Date = "4/27", Topic = "**EXAM 2 due at 11:59 pm**", Deliverables ="",.after = 11)
                      
wk_schedule %>%
  kable("html", align="lllll",linesep = "", caption = "Schedule : **(Deliverables are due before class on the mentioned date)**") %>%
  kable_styling(bootstrap_options = c("hover", "striped", 
                                      "responsive", "bordered")) %>%
  column_spec(c(1,5), bold = T) %>%
  collapse_rows(columns = 1, latex_hline = "major", valign = "middle") %>%
  row_spec(0,bold = T, color = "white", background = "#000000") %>%
  row_spec(c(9,12), bold = T,italic = T)

```
#