---
title: 'GEOG 215: Introduction to Spatial Data Science'
author: "Varun Goel"
date: "Spring 2020"
output:
  html_document:
    theme: flatly
    highlight: tango
    lib_dir: ../site_libs
    self_contained: no
    toc: yes
    toc_float: yes
    css: css/custom_css.css
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse); library(kableExtra);library(stringr); library(pander)
library(lubridate)
#options(knitr.table.format = "latex", knitr.kable.NA = '') 
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE) 
```

# FAQ/tips for success

- Code a little bit every day. Even if you can only find 20 minutes -- write a little bit of code.

- Google is your best friend for solving programming problems. I will repeat this many times.

- If one of the readings isn't satisfying to you go find a different explanation! It often takes 3 different explanations (read multiple times) before I understand an unfamiliar, tricky concept. 

- If you are new to programming the beginning of the course will be a big adjustment. Don't give up, you'll get the hang of it in a couple weeks.

- Coding in general can be very frustrating. Be patient and keep hacking at the problem.

- If you are already familiar with R there is still a lot to learn. For example, if you are not used to the [tidyverse](https://blog.rstudio.org/2016/09/15/tidyverse-1-0-0/) the beginning of course will take some adjustment.

- If you have already machine learning/more advanced statistics courses there will be opportunities for you to use what you have learned/learn new things.

- This class may be quite different from other STEM courses you have taken -- particularly the amount of class participation. [Active Learning](https://en.wikipedia.org/wiki/Active_learning) is backed up by hundreds of studies that show active learning performs better than traditional lecturing on almost every examined learning outcome (see Felder and Brent below).

- If there is something related to data science you want to learn tell me. I can at least point you to resources and may try to include it in the class!